modLoader = "javafml"
loaderVersion = "[41,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "vmtranslationupdate"
version = "${version}"
displayName = "VM Translation Update"
displayURL = "https://github.com/VM-Chinese-translate-group/VM-Chinese-Group-Update"
authors = "Wulian233, TexTrue, Litchiiiiiii"
description = '''
A mod for checking for updates to VM Chinese Group's localization patches
and automatically downloading resource packs.

一个用于检查汉化补丁更新和自动下载资源包的模组。
'''
logoFile = "icon.png"

[[dependencies.vmtranslationupdate]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vmtranslationupdate]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.19.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.vmtranslationupdate]]
modId = "architectury"
mandatory = true
versionRange = "[4,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vmtranslationupdate]]
modId = "cloth_config"
mandatory = true
versionRange = "[6,)"
ordering = "AFTER"
side = "BOTH"
